### ISSUE TITLE
How to implement button with generic static site 

### ISSUE THREAD

**Issue by ghost** [FlipZoomMedia/PageHitCounter#7]
Hi, I'd like to implement a Botton on my static site which shows the viewcount, is this possible with your Script and if yes, how? I'm relativley new to webdev so excuse me if this is a dump question

**Comment by flipzoom** [comment]
Sorry, I don't quite understand your scenario and what is meant by static page. You can get the current counter state via PW access `<?php echo $page->phits; ?>`

**Comment by flipzoom** [comment]
Since there's no feedback here, I'm closing the ticket. If you have further questions, please open it again.
